### ISSUE TITLE
Credentials?

### ISSUE THREAD

**Issue by brianshumate** [emily-plummer/kittenlytics#2]
Hiya Emily,

I would like to try this awesome project out, but I am not sure about the proper format of `creds.json`. After quick glance at the code, I arrived at this:

``` json
{
  "twitter": [
    {
      "consumerKey": "XXX",
      "consumerSecret": "XXX",
      "accessToken": "XXX",
      "accessTokenSecret": "XXX"
    }
  ]
}
```

The app still doesn't work for me with valid values formatted as above though. Can you advise on this and I'll be happy to update the README accordingly and submit a PR.

Meow!

**Comment by andrewvy** [comment]
Hi! You're close, twitter should be an object, rather than an array. :cat: 

```
{
  "twitter": {
    "consumerKey": "xxxx",
    "consumerSecret": "xxxx",
    "accessToken": "xxxx",
    "accessTokenSecret": "xxx"
  }
}
```

**Comment by emplums** [comment]
Hey @brianshumate! Thanks for taking a look! Does it work for you now in the object format?

**Comment by brianshumate** [comment]
:+1: Yes, cool!

**Comment by emplums** [comment]
yay! :fireworks:
